### ISSUE TITLE
Impossible de créer un compte

### ISSUE THREAD

**Issue by VIDUSIN** [ylastapis/blagnacvolley_sf2#40]
En cliquant sur "Créer un compte" :
Fatal error: Class 'BV\FrontBundle\Form\Type\DatePickerType' not found in /home/blagnacvuj/www/app/cache/prod/appProdDebugProjectContainer.php on line 1447

De plus, dans le mode admin en entrant un utilisateur manuellement, pas de moyen de définir le mot d passe :
![image](https://cloud.githubusercontent.com/assets/13104405/8413326/0030b73c-1e90-11e5-97a0-0540f82d362d.png)

**Comment by ylastapis** [comment]
La Création de comptes utilisateurs via l'administration n'est pas fonctionelle a 100% encore, effectivement. C'est quoi l'utilité de créer des comptes via l'admin plutot que de demander aux joueurs de se créer un compte sur le site ?

**Comment by VIDUSIN** [comment]
Tous le monde n'a pas internet. Et d'une manière plus chiante, si tu laisse le choix à un casse couille, il prendra cette option... LOL

**Comment by VIDUSIN** [comment]
A ce jour, ticket toujours pas résolu. A régler en priorité !...

**Comment by VIDUSIN** [comment]
ouppsss...

**Comment by ylastapis** [comment]
@VIDUSIN 
Tu peux détailler ton erreur ? chez moi ca marche bien...

**Comment by VIDUSIN** [comment]
Fatal error: Class 'BV\FrontBundle\Form\Type\DatePickerType' not found in /home/blagnacvuj/www/app/cache/dev/appDevProjectContainer.php on line 839
