### ISSUE TITLE
Perte dans la base de données lors d'évolution du site

### ISSUE THREAD

**Issue by VIDUSIN** [ylastapis/blagnacvolley_sf2#45]
Entre deux déploiements de version du site, est-ce qu'on perd forcement toutes les données saisies ?
Exemples : 
- sur l'ancienne version, j'avais édité des news, et là on est revenu aux anciennes...
- que sont devenus les comptes précédemment créés ?

**Comment by ylastapis** [comment]
J'avais besoin de recréer la base, mais non entre deux versions, on ne perds rien ;)
